### ISSUE TITLE
Cant run either version 4.0, or 3.91

### ISSUE THREAD

**Issue by Axaion** [andymanic/OSRTT#5] opened 2023-02-10 10:56 UTC
getting this error message
"The exception unknown software exception (0x0434352)
occured in the application at location 0x00007FFD65754F99."

**Comment by andymanic** [comment] 2023-02-10 13:23
It might be because I updated the .NET Framework version to 4.8.1 - here's the installer for that: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481
Otherwise it might be worth doing a fresh install of the software as I also updated some of the dependencies. Make sure to backup your results folder before deleting anything!
Let me know if either fix it and I'll close the issue.

**Comment by Axaion** [comment] 2023-02-10 13:28
Just installed both the dev and the normal version of 4.8.1, offline and web install, still the same error :|
also uninstalled and reinstalled osrtt afterwards and the error persists

**Comment by andymanic** [comment] 2023-02-10 14:15
Can you post a screenshot of the error?

**Comment by Axaion** [comment] 2023-02-10 14:17
![image](https://user-images.githubusercontent.com/42967703/218113912-bf1c2ae6-8267-43fb-80c3-dc6c87e052d0.png)
here ya go

**Comment by andymanic** [comment] 2023-02-10 14:46
This isn't an error I can reproduce so it's hard to offer much support. Microsoft forums recommend running check disk and potentially running the repair .NET tool ([https://www.microsoft.com/en-gb/download/details.aspx?id=30135](https://www.microsoft.com/en-gb/download/details.aspx?id=30135)), and rebooting. Does V3.8 still work fine?

**Comment by Axaion** [comment] 2023-02-10 15:28
3.8 launches correctly, just tried installing it

**Comment by andymanic** [comment] 2023-02-10 16:28
Interesting. I have to assume it's an issue with .NET 4.8 on your machine then although I'm not sure what to recommend to fix that beyond the above steps.

**Comment by Axaion** [comment] 2023-02-11 01:31
Yeah i ran the checker too, and chkdsk, nothing seems to fix it .. strange - ill see if i can remember asking anyone else with it if they have the same issue later on!

**Comment by chrisheinonen** [comment] 2023-02-27 19:20
Also having the same issues with 3.91 and 4.0 and have updated to 4.81 runtimes. Here's output from the Windows Event Log:

`Faulting application name: OSRTT Launcher.exe, version: 4.0.0.0, time stamp: 0xec7822b7
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1194, time stamp: 0xfaa44dd0
Exception code: 0xe0434352
Fault offset: 0x000000000009051c
Faulting process id: 0x0x95C
Faulting application start time: 0x0x1D94ADFBC4D377E
Faulting application path: C:\OSRTT Launcher\OSRTT Launcher.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9e291739-bd35-4c21-b42d-7917590d58fe
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by andymanic** [comment] 2023-02-27 21:05
> Also having the same issues with 3.91 and 4.0 and have updated to 4.81 runtimes. Here's output from the Windows Event Log:
> 
> > Faulting application name: OSRTT Launcher.exe, version: 4.0.0.0, time stamp: 0xec7822b7
> > Faulting module name: KERNELBASE.dll, version: 10.0.22621.1194, time stamp: 0xfaa44dd0
> > Exception code: 0xe0434352
> > Fault offset: 0x000000000009051c
> > Faulting process id: 0x0x95C
> > Faulting application start time: 0x0x1D94ADFBC4D377E
> > Faulting application path: C:\OSRTT Launcher\OSRTT Launcher.exe
> > Faulting module path: C:\Windows\System32\KERNELBASE.dll
> > Report Id: 9e291739-bd35-4c21-b42d-7917590d58fe
> > Faulting package full name:
> > Faulting package-relative application ID:

Is that the only event log error that shows up? In theory there should be one listed as a ".NET Runtime" error too. I still have to assume it's a runtime error locally rather than a codebase issue, but I'm still stuck on what the fix is. Do you know if you have multiple versions of the .NET runtime installed? If so can you try uninstalling the older version to see if it's just a compatibility issue?

**Comment by chrisheinonen** [comment] 2023-02-27 21:44
> 

This shows up as well:

> Faulting application name: OSRTT Launcher.exe, version: 4.0.0.0, time stamp: 0xec7822b7
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1194, time stamp: 0xfaa44dd0
Exception code: 0xe0434352
Fault offset: 0x000000000009051c
Faulting process id: 0x0x95C
Faulting application start time: 0x0x1D94ADFBC4D377E
Faulting application path: C:\OSRTT Launcher\OSRTT Launcher.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9e291739-bd35-4c21-b42d-7917590d58fe
Faulting package full name: 
Faulting package-relative application ID:

**Comment by andymanic** [comment] 2023-02-27 23:33
> > 
> 
> This shows up as well:
> 
> > Application: OSRTT Launcher.exe
> > Framework Version: v4.0.30319
> > Description: The process was terminated due to an unhandled exception.
> > Exception Info: System.IO.FileLoadException
> > at OSRTT_Launcher.Main.UpdateMe()
> > at OSRTT_Launcher.Main..ctor()
> > at OSRTT_Launcher.Program.Main()

Interesting - it's failing at the auto updater.. Can you try replacing the contents of your C:\OSRTT Launcher folder with the attached files (except the OSRTT UE4 folder)? I've moved some files around which might be where your install is sticking. [OSRTT Update Files (V4.00).zip](https://github.com/andymanic/OSRTT/files/10845191/OSRTT.Update.Files.V4.00.zip)

**Comment by chrisheinonen** [comment] 2023-02-27 23:49
That fixed it, so I guess we know where the issue is now. Thanks!

**Comment by andymanic** [comment] 2023-02-27 23:50
Perfect, glad it's working! I'll update the release just in case. @Axaion can you try that too?

**Comment by Axaion** [comment] 2023-03-08 09:11
> Perfect, glad it's working! I'll update the release just in case. @Axaion can you try that too?

Sorry, took a bit to get back to you, yeah the linked files and manually overwriting works for me too.

**Comment by andymanic** [comment] 2023-03-08 12:40
No worries - glad that's sorted!

**Closed by andymanic** 2023-03-08 12:40 UTC
Labels: bug
